[global]
ignore_file = "README.md, Makefile.ini, Makefile, configure";
ignore_dir = ".git, build_project, build_dev_shell, env_tools";

[target#0]
target = "";
target_param = "644"
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";
