[global]
ignore_file = "Makefile.ini, Makefile";
ignore_dir = "";

[target#0]
target = "/root/.vim/";
target_param = "644"
target_user = "root";
target_group = "root";
target_dir_param = "755"
target_dir_user = "root";
target_dir_group = "root";
