#!/bin/sh

# vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker:
#
# 用于构建 swansoft rpm 安装包的脚本

#########################################
# 函数部分 ##############################
#########################################

send_mail_success ()
{
t_email_to="xutiangong@eyou.net"
t_email_con_key="[Build RPM] [OK] Build $VERSION_TYPE eYouMail5-$OS_NAME $VERSION_FULL RPM"
t_email_mess="Date: `date -R`
From: RPMBuildServer <rpmbuildserver@rpmbuildserver>
To: $t_email_to
Subject: $t_email_con_key
Content-Type: text/plain; charset=\"UTF-8\"
Content-Transfer-Encoding: 7bit

$t_email_con_key
"
echo "$t_email_mess" | $CMD_SENDMAIL $t_email_to
}

send_mail_fail ()
{
if [[ X"$1" = X"mta" ]]
then
    t_email_to="xutiangong@eyou.net, cress@eyou.net, haozhiqiang@eyou.net"
else
    t_email_to="xutiangong@eyou.net"
fi

t_email_con_key="[Build RPM] [FAIL] Build $VERSION_TYPE eYouMail5-$OS_NAME $VERSION_FULL RPM"
if [[ -f $PATH_WORK_LOG ]]
then
    t_email_body=`tail -n 100 $PATH_WORK_LOG`
else
    t_email_body="$t_email_con_key"
fi

t_email_mess="Date: `date -R`
From: RPMBuildServer <rpmbuildserver@rpmbuildserver>
To: $t_email_to
Subject: $t_email_con_key
Content-Type: text/plain; charset=\"UTF-8\"
Content-Transfer-Encoding: 7bit

$t_email_body
"
echo "$t_email_mess" | $CMD_SENDMAIL $t_email_to
}

check_return_exit ()
{
    if ! test 0 = $?; then
        echo -e "\n!!!!!!!!!! Error, this script will exit !!!!!!!!!!\n"
        send_mail_fail "$1"
        exit 1
    fi
}

cd_work ()
{
    cd $PATH_WORK
}

# 输出停止脚本的提示信息
echo_exit ()
{
    echo -e "\n!!!!!!!!!! Error, this script will exit !!!!!!!!!!\n"
    send_mail_fail $1
    exit 1
}
