#!/usr/local/dev_swan/opt/php/bin/php
<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker: */
// +---------------------------------------------------------------------------
// | SWAN [ $_SWANBR_SLOGAN_$ ]
// +---------------------------------------------------------------------------
// | Copyright $_SWANBR_COPYRIGHT_$
// +---------------------------------------------------------------------------
// | Version  $_SWANBR_VERSION_$
// +---------------------------------------------------------------------------
// | Licensed ( $_SWANBR_LICENSED_URL_$ )
// +---------------------------------------------------------------------------
// | $_SWANBR_WEB_DOMAIN_$
// +---------------------------------------------------------------------------
 
require_once 'dev_core.php';
require_once PATH_DSWAN_LIB . 'sw_create_database.class.php';

/**
+------------------------------------------------------------------------------
* 生成SQL建表语句
+------------------------------------------------------------------------------
* 
* @package 
* @version $_SWANBR_VERSION_$
* @copyright $_SWANBR_COPYRIGHT_$
* @author $_SWANBR_AUTHOR_$ 
+------------------------------------------------------------------------------
*/

$options = getopt('ht:');
$usage = <<<EOD
创建数据库 SQL 语句工具：
	-h 帮助
	-t 创建的类型 swan 产品主表 | unit 单元测试表
EOD;

if (isset($options['h'])) {
	echo $usage , PHP_EOL;
	exit(0);
}

if (isset($options['t'])) {
	switch ($options['t']) {
		case 'unit':
			$file_name = '/root/code/smeta/tests/db_schema.xml';
			$output_name = '/root/code/smeta/tests/';
			break;	
		case 'swan':
			$file_name = '/root/code/smeta/docs/database/db_schema.xml';
			$output_name = '/root/code/smeta/src/tmp_install/sql';
			break;	
		default:
			echo $usage, PHP_EOL;
			exit(1);
	}
} else {
	echo $usage, PHP_EOL;
	exit(1);
}

try {
	$create_database = new sw_create_database();
	$create_database->set_filename($file_name)
					->set_dirname($output_name)
					->run();	
} catch (sw_exception $e) {
	echo $e->getMessage() . PHP_EOL;	
}
