#!/usr/local/dev_swan/opt/php/bin/php
<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker: */
// +---------------------------------------------------------------------------
// | SWAN [ $_SWANBR_SLOGAN_$ ]
// +---------------------------------------------------------------------------
// | Copyright $_SWANBR_COPYRIGHT_$
// +---------------------------------------------------------------------------
// | Version  $_SWANBR_VERSION_$
// +---------------------------------------------------------------------------
// | Licensed ( $_SWANBR_LICENSED_URL_$ )
// +---------------------------------------------------------------------------
// | $_SWANBR_WEB_DOMAIN_$
// +---------------------------------------------------------------------------
 
require_once 'dev_core.php';
require_once PATH_DSWAN_LIB . 'sw_create_database_wiki.class.php';

/**
+------------------------------------------------------------------------------
* 生成MYSQL 数据字典
+------------------------------------------------------------------------------
* 
* @package 
* @version $_SWANBR_VERSION_$
* @copyright $_SWANBR_COPYRIGHT_$
* @author $_SWANBR_AUTHOR_$ 
+------------------------------------------------------------------------------
*/
try {
	$create_database = new sw_create_database_wiki();
	$create_database->set_filename('/root/code/smeta/docs/database/db_schema.xml')
					->set_dirname('/root/code/swan_docs/smeta/source/docs/')
					->run();	
} catch (sw_exception $e) {
	echo $e->getMessage() . PHP_EOL;	
}
