#!/usr/local/swan/opt/php/bin/php
<?php
require_once 'dev_core.php';

require_once D_PATH_SWAN_LIB . 'sw_create_makefile.class.php'; 
try {
	$create_makefile = sw_create_makefile::factory('common');
	$create_makefile->set_root_dir('/usr/local/swan/')->run();	
} catch (Exception $e) {
	echo $e->getMessage() . PHP_EOL;	
}
