[global]
ignore_file = " Makefile.ini, Makefile";
ignore_dir = "";

[target#0]
target = "app/sbin/";
target_param = "755"
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";

[target#1]
target = "/usr/bin";
target_param = "755"
target_user = "root";
target_group = "root";
src_file ="jjcm"
